# Статичные данные
root: ./dist
# Маршрутизация запросов
router:
  pattern: ^\/
  index: index.html
  ipClientHeaderName: 'X-Client-IP'
  location:
    "/":
      url: 'http://localhost:8081'
      remove: false
variables:
  api_url: ''
port: 8080
# Запуск SSL
secure: false
# Путь до сертификатов, не работает при secure = false
certificate:
  cert:
  key:
  client_cert:
timeout:
  read: 30
  write: 30
  idle: 30
# Настройка проверки подключений
heartbeat:
  path: '/heartbeat'
  statusCode: 200
# Прокси клиент
client:
#  maxConnsPerHost: 0
#  maxIdemponentCallAttempts: 0
#  maxResponseBodySize: 0
#  readBufferSize: 0
#  writeBufferSize: 0
#  readTimeout: 0
#  writeTimeout: 0
#  maxConnWaitTimeout: 0
#  streamResponseBody: 0
  tls:
    insecureSkipVerify: true
logger:
  format: "[${time}] ${ip} ${protocol} ${status} - ${latency} ${method} ${url}"
  filename: web
  time:
    # golang time format
    format: 15:04:05
    zone: Local
    # millisecond
    interval: 500